# Generated by Django 5.0.2 on 2024-03-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_cliente_documento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empleado',
        ),
    ]
