# Generated by Django 5.0.2 on 2024-03-16 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_datosextras'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='informacion',
            field=models.CharField(default=datetime.datetime(2024, 3, 16, 1, 51, 59, 287887, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
    ]
