# Generated by Django 5.0.2 on 2024-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_empleado_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
