# Generated by Django 5.0.2 on 2024-03-29 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_empleado_avatar_alter_empleado_fecha_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextras',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
